# Generated by Django 4.2.7 on 2023-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
